version: '3.8'
services:
  test-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - '3307:3306'
  test-redis:
    image: redis:6.2-alpine
    ports:
      - '6389:6379'
    command: redis-server --appendonly yes
